default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_development # ここは任意。もしローカルがSQLiteなら adapter: sqlite3 に戻してください

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
